name: oriens_eam
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_hooks: ^0.20.1
  cupertino_icons: ^1.0.6
  connection_notifier: ^2.0.1
  fluttertoast: ^8.2.4
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.3
  go_router: ^10.1.2
  calendar_view: ^1.0.4
  intl: ^0.19.0
  table_calendar: ^3.0.9
  http: ^1.1.0
  dio: ^5.3.3
  rxdart: ^0.27.7
  persistent_bottom_nav_bar: ^5.0.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  dropdown_search: ^5.0.6
  searchfield: ^0.8.4
  equatable: ^2.0.5
  retrofit: ^4.0.3
  mobile_scanner: ^3.5.5
  image_picker: ^1.0.4
  flutter_form_builder: ^9.1.1
  flutter_pdfview: ^1.3.2
  connectivity_plus: ^2.3.0
  flutter_secure_storage: ^9.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.1.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  simple_barcode_scanner: ^0.0.6
  file_picker: ^8.0.1
  open_file: ^3.2.1
  url_launcher: ^6.0.20
  permission_handler: ^11.3.1
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.2
  build_runner: ^2.4.6
  floor_generator: ^1.4.2
  isar_generator: ^3.1.0+1
  mailer: ^6.0.0
  package_info_plus: ^8.0.3
  device_info_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_hooks: ^0.20.1
  cupertino_icons: ^1.0.6
  connection_notifier: ^2.0.1
  fluttertoast: ^8.2.4
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.3
  go_router: ^10.1.2
  calendar_view: ^1.0.4
  intl: ^0.19.0
  table_calendar: ^3.0.9
  http: ^1.1.0
  dio: ^5.3.3
  rxdart: ^0.27.7
  persistent_bottom_nav_bar: ^5.0.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  dropdown_search: ^5.0.6
  searchfield: ^0.8.4
  equatable: ^2.0.5
  retrofit: ^4.0.3
  mobile_scanner: ^3.5.5
  image_picker: ^1.0.4
  flutter_form_builder: ^9.1.1
  flutter_pdfview: ^1.3.2
  connectivity_plus: ^2.3.0
  flutter_secure_storage: ^9.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.1.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  simple_barcode_scanner: ^0.0.6
  file_picker: ^8.0.1
  open_file: ^3.2.1
  url_launcher: ^6.0.20
  permission_handler: ^11.3.1
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.2
  build_runner: ^2.4.6
  floor_generator: ^1.4.2
  isar_generator: ^3.1.0+1
  mailer: ^6.0.0
  package_info_plus: ^8.0.3
  device_info_plus: ^11.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/poppins/Poppins-Thin.ttf
#          weight: 100
#        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
#          weight: 200
#        - asset: assets/fonts/poppins/Poppins-Light.ttf
#          weight: 300
#        - asset: assets/fonts/poppins/Poppins-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/poppins/Poppins-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/poppins/Poppins-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
#          weight: 800
